# ===============================
# SERVER
# ===============================
server.port=8080
#postgresql://online_auction_ar4k_user:j88UJkTNwZMflSBPPad4ePeVtlM1646n@dpg-d6rsvr9aae7s73cvmasg-a.oregon-postgres.render.com/online_auction_ar4k
# ===============================
# DATABASE - MYSQL
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d6rsvr9aae7s73cvmasg-a.oregon-postgres.render.com:5432/online_auction_ar4k
spring.datasource.username=online_auction_ar4k_user
spring.datasource.password=j88UJkTNwZMflSBPPad4ePeVtlM1646n
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
app.jwt.secret=BidVaultSuperSecretKey2024XYZABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijk
app.jwt.expiration=86400000

# ===============================
# LOGGING
# ===============================
logging.level.com.auction=DEBUG